### ISSUE TITLE
Possibility to randomize image sets

### ISSUE THREAD

**Issue by mariuspedersen** [khaivngo/QuickEval#101]
It would be nice to be able to randomize image sets when setting up the experiment.

**Comment by khaivngo** [comment]
Could you be more specific?

Are you suggesting any of following scenarios;
-Picking a random image set? If so, should the scientist be able to define how many image sets?
-Randomizing images within a chosen image set?
-Randomizing chosen image set(s) but keeping order of images intact?

**Comment by mariuspedersen** [comment]
When you set up an experiment, you can add image sets (set 1, set 2, set 3, etc.). Quickeval will then randomize the images in set 1, show all images in set 1, then it moves on to set 2, then set 3, etc. What would be nice is to have the option to randomize the sets. I.e. do set 3 first, then set 1, then set 2,. That the set order could also be randomized. I believe that this function is not there today. 

Is this understandable?

**Comment by khaivngo** [comment]
If I understand this correctly the images for each included set will be randomized for every time the experiment is done?
In addition you are also saying that the image sets should also be randomized in the order they appear?
