### ISSUE TITLE
Images are shown with a delay

### ISSUE THREAD

**Issue by amirshahi62** [khaivngo/QuickEval#102]
During the test the images were not shown instantly and it took time for it to show up. Loading from the top of the image coming down. I have a good internet speed (50Mbs) so I'm pretty sure this is from your side and not mine.

**Comment by khaivngo** [comment]
Any chance you could provide more information on the experiment?
With which experiment does this happen?
Which browser are you using?
Which operating system?

**Comment by amirshahi62** [comment]
I think the name of the test was: Colour2Gray - web. I followed this link: http://www.ansatt.hig.no/mariusp/quick/index.php?invite=7042527524

Chrome on a windows 10.

**Comment by khaivngo** [comment]
Ran the experiment without being able to reproduce your issue. Not sure what else it could be besides either browser issue, internet speeds or that the server was extra busy at that particular moment.Does this happen for all users every time and for the same experiment?

**Comment by amirshahi62** [comment]
Probably busy issue. I don't know if it happens for all users since I am a user ;)

Just trying to help. Hopefully it does not show up again.

**Comment by khaivngo** [comment]
Of course, appreciate your help. I'm closing the issue for now, but if it occurs again don't hesitate to reopen it.
