### ISSUE TITLE
Editing and link sharing problems 

### ISSUE THREAD

**Issue by mekides** [khaivngo/QuickEval#103]
Hello khaivngo,

I have noticed the following problems.

1. After creating one experiment, there is no option to edit anything. For example, If I want to edit the instruction or the image sets, I have to re-create the whole experiment all over again.  

2. I am doing an online experiment and I have to share a link through e-mail invites. However, when people click the link and login to QuickEval they are not forwarded to the right experiment. I think, during login, it always get set to the home page. Will there be an easy and quick fix for this problem? 

Thanks,

**Comment by khaivngo** [comment]
@mekides 
1. This was the original specification for the application. Any editing must be a feature request for the future and requires considerable amounts of coding.
2. Do you have an example link?
