### ISSUE TITLE
Incomplete data in analysis - possbility to include/exclude

### ISSUE THREAD

**Issue by mariuspedersen** [khaivngo/QuickEval#109]
Some scaling results of unfinished experiments being included in the final experimental analysis and excel file.  One should probably have the option of including/excluding this data on the results page.

**Comment by disastersystem** [comment]
By default unfinished experiments are not used in result statistics, check a checkbox to include them
commit a60a585a4ed2af4809123caeb24924dd28029ff1

Filter out incomplete results when exporting by only selecting values in the observer table with a "completed" value of 1
commit 95e9c6317512c262c1d20bf49014d25b87d4f1f0
