### ISSUE TITLE
Statistics not loading with unfinished experiment

### ISSUE THREAD

**Issue by marcosmg95** [khaivngo/QuickEval#136]
I have created an experiment with the 161 ID and it currently has 4 observers, 1 has completed the experiment and the other 3 not. I am able to see the statistics of this experiment if I uncheck the "Include unfinished experiments in calculations" checkbox. 
![image](https://user-images.githubusercontent.com/41706689/108836483-29830880-75d1-11eb-9588-0d892fd452ed.png)
Otherwise the statistics bar stays loaded forever and the following errors appear in the console on Chrome 88 on Windows 10:

![image](https://user-images.githubusercontent.com/41706689/108836355-07898600-75d1-11eb-8b87-f9ee0756d731.png)

![image](https://user-images.githubusercontent.com/41706689/108836421-1839fc00-75d1-11eb-804d-d8b77264a8cc.png)

I have also tried with Firefox 84 on Windows 10 and this is the error that appears:

![image](https://user-images.githubusercontent.com/41706689/108837219-39e7b300-75d2-11eb-9f87-cd6c0084e1e1.png)

**Comment by mariuspedersen** [comment]
It only calculates results with those who have completed the experiment, and it requires a number of observers to actually do this. So with more observers results should be shown. If you want to look at results early then I would recommend to export and do processing in a third party software.
