### ISSUE TITLE
Unable to continue to the next step when image set is finished

### ISSUE THREAD

**Issue by marcosmg95** [khaivngo/QuickEval#137]
I have created an experiment with the 165 ID (https://quickeval.no/experiment/3/165) with different steps and everything is working correctly. However, after the second step is completed (the first image set) the next button stays loading forever (second capture) and it seems to not be loading the next step (tested with Windows / Chrome 88 and Firefox 84). 

To be able to continue with the experiment and the next step you need to reload the page. Is this the expected behavior?

![image](https://user-images.githubusercontent.com/41706689/108994331-efcb0400-769b-11eb-871c-88ab5b96ee15.png)

![image](https://user-images.githubusercontent.com/41706689/108994180-c0b49280-769b-11eb-8c23-4fa94535104f.png)

**Comment by mariuspedersen** [comment]
I have not experienced this error before, we would need to look into it. @disastersystem : can you have a look?

**Comment by disastersystem** [comment]
@marcosmg95 I've looked into it. It's a bug that was specifically in Category Judgment. I have fixed it. Please try again now.

@mariuspedersen I've rewritten the way the experiment stimuli queue is handled. The new way is much less prone to mistakes like these. And allows for more control handling the queue during experiment setup as well. It will be live in a few days.
