### ISSUE TITLE
Allow the possibility to make the image disappear after some time

### ISSUE THREAD

**Issue by marcosmg95** [khaivngo/QuickEval#138]
Maybe a new feature could be to make available the possibility to make the current image disappear in an experiment after some time if the observer didn’t make a choice in time. For example if an user didn’t click on a category of an image after 2 seconds, advance to the next image. So he is constrained to take the decision with low level information.

**Comment by mariuspedersen** [comment]
Thanks for the suggestion. This is a feature that could be interesting to implement, and I think it could be done with too big problems.

**Comment by disastersystem** [comment]
It's straightforward enough on the implementation side. I can get to it shortly.

One place this can cause problems is if the user uses up/down arrows on the keyboard to select their answer. If the time runs out while the user is tabbing through the list of categories to get to their answer, and we automatically advance to the next image, it may save while on a category the user did not intend to submit as their answer. I will have to think about that.
Could an option be to simply hide the image when time is up, and let the user still rate the image based on their memory of it, before moving on. Or does this defeat the purpose?

**Comment by marcosmg95** [comment]
I think that a good option would also be to just hide the image, so the users can still rate it based on their memory. That way and also knowing the time spent rating each image you would even manage to get more information about their selection. So for example you may remove the observations with more than 2 seconds or 3 based on their memory of the image.
