### ISSUE TITLE
Allow the possibility to choose to use buttons in category judgment instead of a dropdown

### ISSUE THREAD

**Issue by marcosmg95** [khaivngo/QuickEval#139]
Maybe a new feature could be to allow the possibility to use buttons instead of a dropdown in category judgement. So this way it's faster and easier to select a category.

**Comment by mariuspedersen** [comment]
We have discussed this extensively and also tested this, buttons are okay with few categories, but with many they do not fit on the screen. This also depends of course on the description of the categories. Also you can use the keyboard to select the category, there is no need to use the mouse. This feature by using the keyboard is faster than using the mouse (with the dropdown or buttons).
