### ISSUE TITLE
Possibility for multiple scientists for an experiment

### ISSUE THREAD

**Issue by mariuspedersen** [khaivngo/QuickEval#145]
Possibility for multiple scientists for an experiment.

**Comment by disastersystem** [comment]
This feature is live. The invited collaborators will have access to all the observer data and experiment editing rights (only the original owner can delete the experiment). The image/video sets used in the experiment will not be shared though. It might make sense to make those shared as well. Let me know if they should be.

![image](https://user-images.githubusercontent.com/19850690/146857793-5f990a54-b494-45d7-af77-da4a99a796dd.png)
