### ISSUE TITLE
Unexpected colour management applied to PNG images

### ISSUE THREAD

**Issue by gregoryhigh** [khaivngo/QuickEval#149]
Hi,

I've noticed a colour shift when I use PNG files in QuickEval.

Example:
I create an unprofiled PNG with pixel values RGB=[128,128,128], and I upload it to QuickEval.
When the experiment runs the pixel values on the display shift slightly, but enough to be visible.
In my example, it results in a display pixel value of RGB=[129,129,129]!! This is noticeable against the HTML #808080 grey.
This means other colours will also have shifted in an unknown way.

The same problem does not occur with unprofiled JPEG images (the grey is displayed correctly).
Opening the PNG directly from my desktop into my web-browser also gives the correct grey.

Possible cause:
If I had to guess, this is an issue with non-sRGB displays and non-sRGB images, and so probably a profile is being applied somewhere to the PNG images, rather than just sending the raw pixel values to the display.

My workaround is simply to use JPEGs, but I would have preferred to use uncompressed PNG.

Possible solution:
Maybe add a warning for users if they attempt to upload PNGs?

Regards,

Greg

**Comment by mariuspedersen** [comment]
Which browser/OS do you use?

**Comment by mariuspedersen** [comment]
Also is this only in an experiment or in the the "preview" under "my image set?

**Comment by gregoryhigh** [comment]
Hi,

I saw this whilst using MS Edge and Firefox on a Windows 7 PC.
It also occurred on Mac using Safari.

Regards,

Greg

**Comment by gregoryhigh** [comment]
Hi,

 

This was in the experiment (where the background was specified as #808080)

 

Regards,

 

Greg

 

From: mariuspedersen ***@***.***>
Reply to: khaivngo/QuickEval ***@***.***>
Date: Thursday, 27 May 2021 at 20:38
To: khaivngo/QuickEval ***@***.***>
Cc: Gregory High ***@***.***>, Author ***@***.***>
Subject: Re: [khaivngo/QuickEval] Unexpected colour management applied to PNG images (#149)

 

Also is this only in an experiment or in the the "preview" under "my image set?

**Comment by mariuspedersen** [comment]
Do you know or could check if it is also in the preview in the dataset page?

**Comment by gregoryhigh** [comment]
Hi Marius,

 

Rather annoyingly I am unable to replicate the problem this evening at home.

 

However, I have uncovered a bug in Photoshop – when saving an unprofiled file as a PNG, Photoshop embeds an Adobe RGB profile!!! (Photoshop 2021 on Mac)

 

Unfortunately, I deleted previous image sets, so I can’t go back and check, but it maybe these Photoshop saved files were the problem.

 

I apologise for besmirching the good name of QuickEval!

 

I will double-check on the Lab PC tomorrow,

 

 

With kind regards,

 

 

Greg

 

 

 

From: mariuspedersen ***@***.***>
Reply to: khaivngo/QuickEval ***@***.***>
Date: Thursday, 27 May 2021 at 20:44
To: khaivngo/QuickEval ***@***.***>
Cc: Gregory High ***@***.***>, Author ***@***.***>
Subject: Re: [khaivngo/QuickEval] Unexpected colour management applied to PNG images (#149)

 

Do you know or could check if it is also in the preview in the dataset page?

**Comment by gregoryhigh** [comment]
Hi Marius,

I can confirm that the problem is with Photoshop and not QuickEval.

Upon saving the PNG file, Photoshop (22.4.1 for Mac) unexpectedly embeds an Adobe RGB profile into images that are not colour managed.

I think these were the files I was seeing yesterday, and the differences became apparent as I used different displays.

Therefore I humbly request that you archive this thread!

I shall post a bug report to Adobe. It’s worth noting that other users might be inadvertently generating this same problem, particularly if they automate Photoshop to save batches of files.

 

Many thanks,

 

 

Greg
