### ISSUE TITLE
Will not approve accounts

### ISSUE THREAD

**Issue by mariuspedersen** [khaivngo/QuickEval#152]
When clicking approve for new accounts it comes up as
![image](https://user-images.githubusercontent.com/10753554/122645484-174a4e80-d11b-11eb-92af-3387a451ad5f.png)

**Comment by disastersystem** [comment]
It is working for me. But I think I know what happened: The person used a non-existing email address. So the email script that sends the "account approved" confirmation email to the user fails. And the loading spinner is not cleared if there is an error.

They account is still approved, it's just the loading spinner that is never cleared. I've updated the code to clear the loading even if the confirmation email fails.

We should maybe consider only allowing users to register with real in use email addresses in the future.

**Comment by mariuspedersen** [comment]
than I understand, thanks for the reply
