### ISSUE TITLE
Supporting video stimuli - [new feature request]

### ISSUE THREAD

**Issue by davitgigilashvili** [khaivngo/QuickEval#155]
Is it possible to have videos included as the stimuli the same was as static images are now? It needs to support the both: experiments based completely on video stimuli, or the experiments where videos are compared with static images in the same task. 

The videos we will use in experiments will be mostly a-few-second-long low-FPS clips, which won't need much memory. Maximum file size restriction can be set for videos to avoid memory problems. The example of such video is attached. 

https://user-images.githubusercontent.com/89779831/131336282-308f638c-ee7c-4476-b9b4-cd318cb81940.mp4

Thanks, 
Davit

**Comment by disastersystem** [comment]
This has been requested before, so I'll bump this feature up on the priority list. It's not that much work to implement either.

**Comment by davitgigilashvili** [comment]
Cool. Thanks!

**Comment by disastersystem** [comment]
Video stimuli is now supported and things called "image/images" has been renamed to "stimulus/stimuli".
The way it works is video stimuli will autoplay and loop indefinitely. Sort of like a GIF.
Right now videos cannot be paused. Should they be pausable?
