### ISSUE TITLE
Magnitude Estimation Bug

### ISSUE THREAD

**Issue by davitgigilashvili** [khaivngo/QuickEval#162]
It's not possible to add the instructions. If I include the instructions, they are displayed, but I am not able to close the message box with the instructions — and thus the experiment never starts.

So, I mean, pressing "CLOSE" button does not close the message box, and the observer can't proceed with the actual stimuli to scale them. This is only for Magnitude Estimation experiments. For other types of experiments, it works fine. 

![image](https://user-images.githubusercontent.com/89779831/140644560-4e52241c-ab8e-49c4-af37-2ce67c381297.png)

**Comment by disastersystem** [comment]
It's fixed now. It was an easy fix. One line of code that I had forgotten to comment out. 😁
