### ISSUE TITLE
Results not shown 

### ISSUE THREAD

**Issue by mariuspedersen** [khaivngo/QuickEval#164]
It seems that for newer experiments the results are not shown .

![image](https://user-images.githubusercontent.com/10753554/143002927-74103219-3325-4d23-b28f-c32e4b33f309.png)

**Comment by disastersystem** [comment]
I wasn't able to reproduce this on the live server, but I was able to reproduce it locally. I've done a small update that might have fixed it now, could you check if it's working for you?

**Comment by mariuspedersen** [comment]
Perfect. Works for me now.
