### ISSUE TITLE
Change user access does not work

### ISSUE THREAD

**Issue by mariuspedersen** [khaivngo/QuickEval#18]
I tried to change user access for a user from "observers" to "scientist", but it does not change. It seems like it is not updated in the database.

**Comment by mariuspedersen** [comment]
This is still a problem. I'm not able to change user access on www.colourlab.no/quickeval, I had to do it manually in PhPmyadmin

**Comment by khaivngo** [comment]
Which commit is currently on server? Can confirm that commit a4a4488544ec30cd758fb464728c4d50c46a87bc is fully working for updating user access level, both for downgrading and upgrading user.

**Comment by mariuspedersen** [comment]
That is the commit that is uploaded now. I cannot see that the usertype is changing in the database, but I do get a confirmation from the webpage that it changes.

**Comment by mariuspedersen** [comment]
I tested this with my local installation, and it works. I tried again on the version on http://www.ansatt.hig.no/mariusp/quick/index.php, and it does not work. I do not know why...

**Comment by khaivngo** [comment]
I'll have another look at it.

**Comment by khaivngo** [comment]
@mariuspedersen try it now.

**Comment by mariuspedersen** [comment]
@khaivngo Still does not work. No idea why....
