### ISSUE TITLE
Rank Order - Results - Raw data not displayed correctly 

### ISSUE THREAD

**Issue by mariuspedersen** [khaivngo/QuickEval#26]
The raw data from rank order experiments are not displayed correctly. For the first image nothing is shown (see attached image). While for the second image, the data from the first and second is shown. 

![untitled-1](https://cloud.githubusercontent.com/assets/10753554/6076054/269d85da-adde-11e4-9545-a08637dce268.png)

**Comment by khaivngo** [comment]
Not necessarily isolated to rank order.
