### ISSUE TITLE
Subjective data missing from the reports

### ISSUE THREAD

**Issue by ghost** [khaivngo/QuickEval#34]
In the scientist mode, I incorporated 10 image groups in one experiment. Then, in the observer mode, as an observer I did give ratings on all of them. But the online and exported reports gave results only for group 2 to 10. The results for group 1 were missing. Perhaps you can have a try on the experiment “Perceived Projection Contrast”. It is available on the website: http://www.ansatt.hig.no/mariusp/quick/index.php

![web_version](https://cloud.githubusercontent.com/assets/9220129/6094809/19d7a970-af3c-11e4-83af-8b83c3eb491a.png)

![excel_version](https://cloud.githubusercontent.com/assets/9220129/6094810/20da5c90-af3c-11e4-9bc3-127b295c2e9d.png)

**Comment by khaivngo** [comment]
@ping-zhao I assume the group you are referring to is the same as a picture set?
Is this limited to when there are multiple picture sets or does it also happend when there are only one picture set?

**Comment by khaivngo** [comment]
@mariuspedersen @ping-zhao What is status on this? is it still occurring if so, are there any more details on it?

**Comment by mariuspedersen** [comment]
I did a small test, and in my test everything was okay (but that was just a minor test). It should probably be tested more.
