### ISSUE TITLE
Test images cannot be displayed in a completely randomized order

### ISSUE THREAD

**Issue by ping-zhao** [khaivngo/QuickEval#36]
There is no option to display test images in a totally randomized order at the initial status of the experiments. The shuffled order should be carefully recorded and reflected in reports. Now it simply displays the images with respect to the original uploading order. If the scientist manually change the uploading order of test images, then the calculated Z-scores presented in the reports are useless.

**Comment by mariuspedersen** [comment]
This issue has been fixed, but the more recent code has not been uploaded to the server.

**Comment by khaivngo** [comment]
Please review posted and closed issues before posting new ones. This has been resolved with #19
