### ISSUE TITLE
Image numeric indicators are displayed incorrectly

### ISSUE THREAD

**Issue by ping-zhao** [khaivngo/QuickEval#51]
I am using rank order experimental method. At the initial state, the numeric indicators of image distortions are displayed in a completely randomized order, but once the observer drag and drop any distorted image the numerical indicators return to ranked order, however the actual image distortions do not. This observation does not apply to the first test image data set.

Initial state:

![1](https://cloud.githubusercontent.com/assets/9220129/6258468/07fc49be-b7c9-11e4-9db6-134d8c16f24a.jpg)

Move any one image in front of another:

![2](https://cloud.githubusercontent.com/assets/9220129/6258481/19f034dc-b7c9-11e4-9b26-ef2586d4ec15.jpg)

**Comment by mariuspedersen** [comment]
I was able to recreate this bug (with the numbers not showing up in ascending order in the experiment "test rank order"). (link http://www.ansatt.hig.no/mariusp/quick/index.php?invite=8d80154a36)
