### ISSUE TITLE
When the background is changed to black the label below the image is still black. 

### ISSUE THREAD

**Issue by mariuspedersen** [khaivngo/QuickEval#53]
When the background is changed to black the label below the image is still black. Also the panner is the "default" color, this should also change with what one has defined. 
![quickevalblack](https://cloud.githubusercontent.com/assets/10753554/6265236/40815758-b82c-11e4-9b8b-0400dd655906.png)

**Comment by khaivngo** [comment]
@mariuspedersen: Should the background color of the thumbnail-container still be a few shades darker of the overall color as it is now, or should the container have the same color as the background color and outline the container with a border?

**Comment by mariuspedersen** [comment]
Maybe it should be slightly different in order to know where to drop the images. Otherwise it would be difficult to see where to drop the images.

**Comment by khaivngo** [comment]
What about instruction and other popups for the experiment, should they retain their color or also shift with the background?

**Comment by mariuspedersen** [comment]
I think they can stay the same color as they are today. I do not see a reason why they need to change.
