### ISSUE TITLE
Scaling of images 

### ISSUE THREAD

**Issue by mariuspedersen** [khaivngo/QuickEval#54]
There still seems to be a problem scaling of images in QuickEval. The images are not shown as one-pixel-to-one-pixel. They are rescaled right now.

**Comment by khaivngo** [comment]
Does this apply to every picture size/dimensions or does it only happen for pictures who are large and have panning?

**Comment by mariuspedersen** [comment]
At least to those that are large and have panning.

**Comment by khaivngo** [comment]
@mariuspedersen try with this one: 54eeb35aa98d5f565f5b13e99976d44142099590
Have of now no good explanation for why it returned, have to keep an eye on it for any further changes.

**Comment by mariuspedersen** [comment]
I have checked this, and it is still a problem. For smaller images (300x300 pixels) and smaller no scaling is done, for larger images (800x800 pixels) the images shown in the "panner" is scaled down. Happens for me both in chrome and IExplore

**Comment by khaivngo** [comment]
Not sure what else is the problem, have tried it with various pictures and the images are able to match up. Need to have a look at your system.

**Comment by mariuspedersen** [comment]
I have tried this again on two different computers, and the images are still scaled... I will try another one tomorrow in the lab so see, but I think that it is still a problem

**Comment by mariuspedersen** [comment]
Tried it on two different computers, and still an issue. @khaivngo Could you log in and check the experiment "Match legend and patch" and see if it scales?

**Comment by khaivngo** [comment]
Will have a look at it by the end of the week.

**Comment by khaivngo** [comment]
@mariuspedersen I have checked and the images are definitely scaled up for the panning area. Have also checked other experiment and the scaling seems to be an issue across the experiment types. Will look further into it.

**Comment by mariuspedersen** [comment]
@khaivngo Have you been able to look further into this? Anything that I can do to help?

**Comment by khaivngo** [comment]
@mariuspedersen Plan to have another go at it this week. The status from last time was that there have not been any changes to the scaling options nevertheless scaling has somehow happend.

**Comment by mariuspedersen** [comment]
Linked with the scaling of images is the size of the image. If the original is not shown, then the two reproduction (or box with the images) be larger. Would it be possible to include a check so that if the original is not shown then the image box could be larger. 1366x768 is the most common resolution today, so the images could potentially be up to 600x600 without introducing the "panning" function. If the original is shown then the image box should be around 400x400 (or potentially 400x600, since only one is shown vertically). Would this be possible to include? It might be that this should be it's own issue.

**Comment by khaivngo** [comment]
But they are never the correct size or are they the correct size when the original is present?
The box could be larger if the original is not present.

**Comment by mariuspedersen** [comment]
Right now, I think they they are never the correct size. My previous reply, was an additional "request", that is not directly related to the scaling issue.

**Comment by khaivngo** [comment]
I see, I'll open a separate issue for the increasement of the view area. Is this a request that is needed for all experiment types?

**Comment by mariuspedersen** [comment]
That should be for all experiment types. For rank order the images might need to be smaller to fit the "order pane" at the bottom.

**Comment by khaivngo** [comment]
Solved in 9390eb02bdc9afbd9c7a440aed1ddc6e4d8c1c5b
