### ISSUE TITLE
Difficult to move images in the rank order mode

### ISSUE THREAD

**Issue by ghost** [khaivngo/QuickEval#69]
In the ranking order experimental mode, the majority of observers complained about the difficulty to drag and drop image distortions in order to rank them, especially in the case the observer try to move images very quickly. The space for insertion does not show up when the mouse move over. Sometimes, the observer has to move mouse pretty much to the left or right where is away from the insertion point then the space will actually show up. This can be difficult for many observers who use QuickEval for the first time. I boldly guess that this might be related to the display resolutions. I use projectors a lot, when the VGA cable is used most likely the resolution is around 1366x768, 1280x768 and 1024x768 etc. Probably the implementation of bounding box detection in JavaScript is using absolute values which were designed for higher display resolution.

**Comment by khaivngo** [comment]
Fixed in b0312b4a3cc78a693f7d2a4c6050e38e9dbb367b
