### ISSUE TITLE
Surprisingly moved image distortions

### ISSUE THREAD

**Issue by ping-zhao** [khaivngo/QuickEval#70]
In the rank order experimental mode, we have 7 distortion levels and we are using display resolution 1280x768. Many observers tried to move the distorted image in the rank position 7 to the observation window on the left. If the mouse moves directly from rank position 7 to the left observation window, the image distortion in the rank position 6 and 7 very likely will surprisingly switch their positions. Depends on how the observer actually move the mouse, sometime the image distortion in the rank position 7 will  be even inserted in front of 5. Then the observers are forced to re-rank the image distortions from level 5 to 7 again. This can be frustrating for observers who prefer to rank very quickly. One of the observers even went mad and almost quit from the experiment because of this. I understand this can be very tricky to fix. Is it possible to replace the drag and drop mechanism with for example double clicking or alternative ways to implement. The ultimate goal should be reducing the workload of observers as much as possible, then they will be happy and positive to participate in more subjective experiments in the future.

**Comment by khaivngo** [comment]
The applicatin have bee developed for full HD in mind. This is a issue we are known with and will be an issue if scaling to viewport size is to be maintained.
