### ISSUE TITLE
Table formatting issue

### ISSUE THREAD

**Issue by mariuspedersen** [khaivngo/QuickEval#73]
After the last development branch, there is an issue with the "formatting" of tables. Scrollbars appears in all tables, even if they are not needed. See attached image. 
![qe_format](https://cloud.githubusercontent.com/assets/10753554/7469897/a5188f98-f318-11e4-9627-ef5797fad107.png)

**Comment by khaivngo** [comment]
Please use branch develop2

**Comment by mariuspedersen** [comment]
The issue is also in this branch.

**Comment by mariuspedersen** [comment]
Are you sure that this fixes the scrollbar issue? I checked this, and the scrollbars are still there.
