### ISSUE TITLE
Paired comparison - same image evaluated against itself

### ISSUE THREAD

**Issue by mariuspedersen** [khaivngo/QuickEval#77]
Sometimes in pair comparison the same image is evaluated against itself. For example if you have images A,B and C. Then it might happen that you are shown "Image A" vs. "Image A". This should not happen. As far as I could identify it does not happen all the time.

**Comment by jehans** [comment]
Do you have an experiment on the liveserver in which this happens so I can recreate the bug?

**Comment by mariuspedersen** [comment]
You might need to test several times, but it happens in experiment "DH2".

**Comment by jehans** [comment]
Bug identified. Fixing ASAP.

**Comment by mariuspedersen** [comment]
@jehans : any updates on this?

**Comment by jehans** [comment]
Starting tomorrow, after my last exam.

**Comment by mariuspedersen** [comment]
I will ask about this again. We have a student who will use paired comparison for his last experiment in the master thesis. This is quite urgent, in term of time. So is there any updates on this? if not, then we need to look at other options.

**Comment by jehans** [comment]
Testcode is ready. Will test it and upload before 2400 today, so that the student is able to use Quickeval.

**Comment by mariuspedersen** [comment]
Thanks a lot!

**Comment by jehans** [comment]
See the latest commit in Develop2.
Let me know if you find any bugs, or if you can confirm that it works properly now!
It did in my testing, but some bugs might occur.
Will be idle at the computer tonight to make sure that this issue is properly fixed before tomorrow.

**Comment by mariuspedersen** [comment]
I tested it this morning, and it seems to work well (no duplicate pairs shown). There is one small thing, it seems like the results are stored differently from before. If you have image A and image B, if you select A, then B in incremented with "1). I cannot remember that this was the case earlier. However, when reading the description in the "I" symbol it seems to be correct. So we will need to change the z-score calculation (This will probably be done by me).

**Comment by khaivngo** [comment]
Is there anything else missing from our part on this particular issue?

**Comment by mariuspedersen** [comment]
No, I do not think so.

**Comment by mariuspedersen** [comment]
This issue should be fixed now, with my latest correction to the z-score calculation.
