### ISSUE TITLE
Error creating experiments

### ISSUE THREAD

**Issue by mariuspedersen** [khaivngo/QuickEval#82]
After I downloading the newest version, I get an error when creating experiments. I tried to remove the database, and re-install it, still the same error. Not sure what the problem is. Tried all three experiment types. 
![errorcreatingexperiment](https://cloud.githubusercontent.com/assets/10753554/8020411/ccb3ab96-0c77-11e5-9243-7045407d43e0.png)

**Comment by khaivngo** [comment]
Could you mail me the DB-dump you are using?

**Comment by khaivngo** [comment]
Which DB-dump are you using?

**Comment by khaivngo** [comment]
3b799fbc298dc9b6ed2240841c8055f62208711e provides new dump which should solve it.
