### ISSUE TITLE
Rank order - missing next/finished button

### ISSUE THREAD

**Issue by mariuspedersen** [khaivngo/QuickEval#84]
The next/finish button is missing in rank order experiment. There is no way to end the experiment. 

The button to show the images in fullscreen is also "misplaced" (at least on my computer). 
![romissingbutton](https://cloud.githubusercontent.com/assets/10753554/8024751/b58f3efe-0d3e-11e5-8fd7-b1b463e56a4d.png)

**Comment by khaivngo** [comment]
Fixed the next-button, but is having a hard time reproducing the fullscreen-button. What resolution are you on?

**Comment by mariuspedersen** [comment]
Resolution 1920x1080.

**Comment by khaivngo** [comment]
Test it now, the fastest fix was to reenable panning for small images but setting on automatic reset of posistion on the panning.

**Comment by mariuspedersen** [comment]
Works perfectly. Thanks.
