### ISSUE TITLE
Rank order problem - no reset button and difficult to move thumbnails

### ISSUE THREAD

**Issue by mariuspedersen** [khaivngo/QuickEval#86]
![untitled-1](https://cloud.githubusercontent.com/assets/10753554/8278148/710576ea-18c9-11e5-8cd7-58c36f3d8215.jpg)
In rank order there is no reset button, and with large images you cannot scroll the entire image. Could you look at this. 

Also with low resolutions it is impossible to drag the thumbnails in the bottom (in this case 1366 x 768).

**Comment by khaivngo** [comment]
The issue with no reset button should not be present in the most recent commit 9bd895732cb96d343c15a68d36857bc58fdc499f

With impossible to drag thumbnails do you mean they can not be dragged, lack of space or hard to reach?

**Comment by mariuspedersen** [comment]
the reset button appears in pair comparison, but not in rank order experiments. 

The tumbnails can be dragged, but they cannot be "dropped". I.e. they do not change the order. This is as far as I can see due to the lack of space.

**Comment by khaivngo** [comment]
See if this solves it: 3cd1281758d15e71355918a1a897c840faeb203f

**Comment by mariuspedersen** [comment]
The reset button is now there. There is another issue, that the panning when you release the mouse button moves the image back to the original position. In larger images it is impossible to scroll to the opposite side.

**Comment by khaivngo** [comment]
Thought that was removed in last commit, this one has the automatic panning
reset feature disabled: 9a410841a074acd7177875f61a56aa310670daa3
