### ISSUE TITLE
New rank order sorting - drag/drop to view image does not work

### ISSUE THREAD

**Issue by mariuspedersen** [khaivngo/QuickEval#90]
The new drag/drop based on rubaxa does no longer allow to drag/drop the image from the bottom to the panner.

**Comment by khaivngo** [comment]
This applies for the latest commit? 6cbe470af2cb5f93dfd5bb8a4a23fbcb1b9e496c

**Comment by mariuspedersen** [comment]
Yes, at least on my system.
