### ISSUE TITLE
Category judgement: Uncaught ReferenceError: Sortable is not defined

### ISSUE THREAD

**Issue by mariuspedersen** [khaivngo/QuickEval#92]
There is a problem in category judgement. It does not show images, and the error shown is "Uncaught ReferenceError: Sortable is not defined"  ratingExperimentScript.js:26

**Comment by mariuspedersen** [comment]
After the fix of the rank order (commit 90) it seems like the image is shown, but the "next" button and the "reset panning" button is missing.

**Comment by khaivngo** [comment]
I'm having a hard time reproducing the problem, could it be local caching issues? Try using incognito(ctrl+shift+n) if you are on Google Chrome.

**Comment by mariuspedersen** [comment]
In the latest version (after commit 90) I cannot recreate the referenceerror. However, for me the buttons are missing (see attached picture). Also, the planning does not work in IE, but it is working in chrome. 
![catjudgemissingbutton](https://cloud.githubusercontent.com/assets/10753554/19835055/c6fd7c18-9e7a-11e6-8094-99341a7ba4f0.png)

**Comment by khaivngo** [comment]
@mariuspedersen try with the latest commit: 45ac8dbb4df9a4511f654468a7a721bba52fd78b

**Comment by mariuspedersen** [comment]
Now it shows the button and the dropdown for the category, but the images are not shown, and the dropdown for the category is blank. 
![catproblem](https://cloud.githubusercontent.com/assets/10753554/19835472/68275dcc-9e88-11e6-8b8b-c456f61a0551.png)
