### ISSUE TITLE
"No results yet" even if there are results

### ISSUE THREAD

**Issue by mariuspedersen** [khaivngo/QuickEval#99]
Even if there are results, no results are shown. 
![noresultsyet](https://cloud.githubusercontent.com/assets/10753554/19835502/4a8e7a38-9e89-11e6-8399-7a897fcccde2.png)

In console.log I get the following message "http://localhost/QuickEval-develop2/js/scientist/experimentResults.js Failed to load resource: the server responded with a status of 404 (Not Found)" 

Update: I think that the console message is not linked with displaying the results, but rather when you go into the "Scientist mode".

**Comment by khaivngo** [comment]
Seems to be an issue with missing plugin, math.js.

**Comment by khaivngo** [comment]
Commit 08827fa2cbd2ba3ae3a86f92f7f577ed36c5d568 includes the missing file.

**Comment by mariuspedersen** [comment]
Seems to work now. Thanks!
